// You can edit this file.
// This is a simple conversion script which uses Regular Expression.
// If additional conversions are required, please add it as you wish.

const fs = require("fs");

const BASH_ROOT = "C:/msys64";
const BASH_HOME = "C:/msys64/home/owner";

const src = process.argv[2];
const dest = process.argv[3];

try {
  const bash = fs.readFileSync(src, "utf8");
  let pwsh = convert(bash);

  pwsh =
    `\
# This file is auto generated by bash2pwsh.js

` + pwsh;

  fs.writeFileSync(dest, pwsh);

  console.log(`"${dest}" was created Successfully!`);
} catch (err) {
  console.log("Error : " + err.message);
}

/**
 * Convert bash script to powershell script.
 * @param {String} bash bash script body
 * @returns powershell script body
 */
function convert(bash) {
  #!/bin/bash



SOURCE_DIRECTORY=$1
BUILD_DIRECTORY=$2
CMAKE_ARGS=$3
GENERATOR="Ninja"
CMAKE_ARGS_=${CMAKE_ARGS// / -D}
echo "$CMAKE_ARGS"
echo "$CMAKE_ARGS_"



if [[ -z "$SOURCE_DIRECTORY" || -z "$BUILD_DIRECTORY" ]]; then
    echo "config.sh <SOURCE_DIRECTORY> <BUILD_DIRECTORY> <CMAKE_ARGS>"
else
    rm -rf $BUILD_DIRECTORY/CMakeCache.txt
    rm -rf $BUILD_DIRECTORY/CMakeFiles/
    cmake -S $SOURCE_DIRECTORY -B $BUILD_DIRECTORY -G $GENERATOR $CMAKE_ARGS_
fi
